name: build
on: [ push, pull_request ]
permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install poetry
              run: pipx install poetry
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: 3.10.13
                cache: 'poetry'
            - name: Install ci deps
              run: poetry install --with dev
